### PR TITLE
Use undocumented View.close method in `close_view`.

### PR DESCRIPTION
**Pull request by Thom1729**
Much better than the old approach.

### CODE REVIEW

**Comment by FichteFoll** [comment]
Can you confirm that this works as expected? I seem to remember issues with `view.close`, but not exactly which. Maybe when the view is inactive?

**Comment by Thom1729** [comment]
It seems like the behavior of `view.close()` is as follows:

- If the view is invalid or cannot be closed (e.g. a panel), return False.
- If the view has unsaved changes and is not a scratch view, display the "save changes?" dialog. If cancelled, return False.
- Finally, close the view and return True.

In particular, the method can "hang" while the dialog is open. Eventually, it will return True or False to indicate whether the view was closed as a result of the call.

I have tested inactive views and had no problems so far.

The `close_view` method never triggers the dialog, because if there are unsaved changes it will either discard them or raise `ValueError`.

**Comment by FichteFoll** [comment]
Okay, this sounds good. 

I believe we can use the return value of `View.close`, however. We could either raise an exception if it's `False` or just forward its return value. The problem with forwarding would be that we already raise an exception if closing failed due to the view being dirty, so we'd have two ways of signaling failure.

**Comment by Thom1729** [comment]
Raising an exception makes sense. Can you think of any way to test this?

**Comment by FichteFoll** [comment]
Just use direct ST api to make the close call return False?

>- If the view is invalid or cannot be closed (e.g. a panel), return False.

**Comment by Thom1729** [comment]
I realized that most of the error handling in that function was redundant, so now the existing tests will be using the new error path. I also added a test for closing an already-closed view.

**Comment by FichteFoll** [comment]
All right, this is good.

However, unfortunately it seems that the branch got messed up. You can merge once you rebased (as I'll be leaving now).

**Pull request merged**
