### PR TITLE
Reformat docs.

### PR DESCRIPTION
**Pull request by Thom1729**
For #74.

Docs are now on a single page.

I totally redid the theme. The “Read the Docs” theme was very noisy. We can add more ornamentation as desired.

Notably, I removed the search function. With all the docs on one page, the browser's built-in search is good enough.

Feedback requested on organization and aesthetics.

### CODE REVIEW

**Comment by Thom1729** [comment]
@evandrocoan Thoughts?

**Comment by FichteFoll** [comment]
Liking the new simple layout, but I'm missing some kind of introduction paragraph before we're going straight at the module docs. At least something like we have in the readme, imo.

**Comment by evandrocoan** [comment]
> FichteFoll: Liking the new simple layout and toc, but I'm missing some kind of introduction paragraph before we're going straight at the module docs. At least something like we have in the readme, imo.

The Sphinx builder could copy the README.md, or at least some delimited part of it into the generated html.


> Thom1729: @evandrocoan Thoughts?

I never worked with Sphinx so far, then, I missed something like a `Makefile` on the `docs` directory:
image

After searching for Sphinx, I found this http://www.sphinx-doc.org/en/1.5/tutorial.html and used this command `sphinx-build -b html source builddir`

This is the quick make file I came up with:
```Makefile
## Usage:
##   make <target> [options]
##
## Targets:
##   all               generate the documentation on the builddir directory
##   help              show this usage help
##
## Options:
##   -p                show all commands run by make, including all variables
##   -n                similar to --dry-run, it will only display the commands,
##                     but not run them.
##
## For more explanations see:
##   http://www.oreilly.com/openbook/make3/book/ch12.pdf
all:
	sphinx-build -b html source builddir

# Print the usage instructions
# https://gist.github.com/prwhite/8168133
help:
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//'
```

If I did it right, this was the result:
image

I did not had though about adding a sidebar table of contents. Nice idea. Optionally, I think it would be nice if the sidebar had a indicator, pointing to where I am on the page while I am "scrolling" around. For example:
fsg

I found this example on:
1. https://stackoverflow.com/questions/27610892/highlight-menu-on-scrolling-if-reach-div
1. http://jsfiddle.net/vu6hN/28/

**Comment by Thom1729** [comment]
There's a Makefile in the package root — just run `make html`. Your build looks right, though.

I like the scrolling idea. I think I might try to remove more of the original theming before adding new functionality. This could be done in a patch release, I assume.

**Comment by evandrocoan** [comment]
I just found another example for the table of contents: 
1. https://apps.ankiweb.net/docs/changes.html#changes-in-2.1.0
1. fsg

**Comment by FichteFoll** [comment]
As we develop more and more, we might need to start thinking about versioning the docs on `gh-pages` or only updating them when a tag is pushed. Currently, it will always build and render docs from `master`.

Feel free to create an issue for this if you consider this to be worthwhile, @Thom1729.

For the TOC-suggestion, see #84.

**Pull request merged**
